[profile.default]
src = "contracts/src"
script = "script"
out = "out"
test = "test"
libs = ["contracts/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
